export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 20,

  PRIMARY_COLOR: '#175043',
  PRIMARY_COLOR_DIMMED: '#739990',
  SECONDARY_COLOR: '#CEE1DD',
  BACKGROUND_COLOR: '#EEFBF8',
};
