export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 20,

  PRIMARY_COLOR: '#175043',
  PRIMARY_COLOR_75: '#4d7b70',
  PRIMARY_COLOR_DIMMED: '#739990',
  SECONDARY_COLOR: '#CEE1DD',
  BACKGROUND_COLOR: '#EEFBF8',

  CARD_BACKGROUND_COLOR: 'white',
  CARD_BORDER_COLOR: '#C4C4C4',
  CARD_BUTTON_COLOR: '#FAEDCD',

  POST_BACKGROUND_COLOR: '#dff7f1',

  NEW_BADGE_COLOR: '#2D8CFB',

  SPACING_SMALL: 8,
  SPACING_MEDIUM: 16,
  SPACING_LARGE: 24,

  BRONZE: '#6A3805',

  // modal button colors
  RED_COLOR: '#c86463',
  GREEN_COLOR: '#4d7b70',
};
